// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, fs, port, readStaticPage;

  express = require('express');

  fs = require('fs');

  app = express.createServer(express.logger());

  app.get('/', function(request, response) {
    return response.send(readStaticPage('index.html'));
  });

  port = process.env.PORT || 5000;

  readStaticPage = function(file) {
    file = 'static_pages/' + file;
    return fs.readFileSync(file, 'utf8');
  };

  app.listen(port, function() {
    return console.log("Listening on " + port);
  });

}).call(this);
